version: '3'  # version of compose format 

services:
  flask-service:
    build: ./app  # path is relative to docker-compose.yml location
    volumes:
      - ./app:/usr/src/app # mount point
    ports:
      - 5000:5000  # host:container
