version: '3'  # version of compose format 

services:
  observatory-service:
    build: ./app  # path is relative to docker-compose.yml localtion
    volumes:
      - ./app:/usr/src/app # mount point
    ports:
      - 5001:80  # host:container
